version: '2'

services:

  dev:
    image: datadog/dev:base
    build: dev
    volumes:
      - ./dev/lifecycle:/opt/lifecycle
      - .:/go/src/github.com/jancajthaml
      - ./vendor/github.com/ScottMansfield:/go/src/github.com/ScottMansfield
      - ./vendor/golang.org:/go/src/golang.org
      - ./src/datadog-mock:/go/src/datadog-mock
    working_dir: /go/src/github.com/jancajthaml
    environment:
      - GOOS
      - GOARCH
      - GOPATH=/go
    entrypoint: /bin/sh
    privileged: true

  sync:
    extends: dev
    image: datadog/dev:sync
    entrypoint: govendor
    command: ["sync", "-v"]

  fmt:
    extends: dev
    image: datadog/dev:fmt
    entrypoint: gofmt
    command: ["-w", "."]

  lint:
    extends: dev
    image: datadog/dev:lint
    entrypoint: go
    command: ["vet", "./..."]

  package:
    extends: dev
    image: datadog/dev:package
    entrypoint: ["/opt/lifecycle/package"]

  test:
    extends: dev
    image: datadog/dev:sync
    entrypoint: ["/opt/lifecycle/test"]

  artefact:
    restart: unless-stopped
    image: datadog/mock:latest
    logging:
      driver: none
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8125:8125/udp"
