version: 2

jobs:
  test:
    docker:
      - image: circleci/golang:1.9
        environment:
          - LANG: C.UTF-8

    working_directory: /go/src/jancajthaml
    steps:
      - checkout

      - run:
          name: Sync dependencies
          command: |
            go get -u github.com/kardianos/govendor
            go get -u golang.org/x/tools/cmd/cover
            go get -u github.com/mattn/goveralls
            govendor sync -v

      - run:
          name: Run tests
          command: |
            cd /go/src/jancajthaml/src/datadog-mock
            : > /go/src/jancajthaml/coverage.txt
            go test -v -cover -race -coverprofile=/go/src/jancajthaml/coverage.txt -covermode=atomic ./...
            goveralls -coverprofile=/go/src/jancajthaml/coverage.txt -service=circle-ci -repotoken=$COVERALLS_TOKEN

      - run:
          name: Build server
          command: |
            cd /go/src/jancajthaml/src/datadog-mock
            go clean
            CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /go/src/github.com/jancajthaml/target/datadog_mock

      - persist_to_workspace: 
          root: /go/src/github.com/jancajthaml
          paths:
            - target/datadog_mock

  deploy:
    docker:
      - image: docker:17.09.0-ce-git
        environment:
          - LANG: C.UTF-8

    working_directory: /app
    steps:
      - attach_workspace:
          at: /go/src/github.com/jancajthaml

      - checkout
      - setup_remote_docker

      - run:
          name: Build application Docker image
          command: |
            cp -r /go/src/github.com/jancajthaml/target /app/target
            docker build \
              --build-arg VERSION=$(git tag | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+$" | sort -t. -k 1,1n -k 2,2n -k 3,3n | tail -1) \
              --build-arg SOURCE=$(git config --get remote.origin.url) \
              -t bundle .

      - deploy:
          name: Push image to DockerHUB
          command: |
            docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}

            if git log -1 --pretty=%B | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+$"; then
              VERSION=$(git tag | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+$" | sort -t. -k 1,1n -k 2,2n -k 3,3n | tail -1)
            else
              VERSION="snapshot.${CIRCLE_SHA1}"
            fi

            docker tag bundle "jancajthaml/datadog_mock:${VERSION}"
            docker push "jancajthaml/datadog_mock:${VERSION}"

      - deploy:
          name: Notifying microbadger to update badges
          command: |
            apk --no-cache add curl
            curl -X POST https://hooks.microbadger.com/images/jancajthaml/datadog_mock/${MICROBADGER_TOKEN}

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
